version: '2'
services:
    web:
        build: .
        ports:
                - "18080:18080"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
